package com.ad364.guided_rule;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String firstName;
	private java.lang.String lastName;
	private java.lang.Boolean isNewhire;

	public Employee() {
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.Boolean getIsNewhire() {
		return this.isNewhire;
	}

	public void setIsNewhire(java.lang.Boolean isNewhire) {
		this.isNewhire = isNewhire;
	}

	public Employee(java.lang.String firstName, java.lang.String lastName,
			java.lang.Boolean isNewhire) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.isNewhire = isNewhire;
	}

}